#!/usr/bin/env python

import os
import argparse
from biomerger import merger
import sys

def create_argparser():
    parser = argparse.ArgumentParser(
        description='fastq merger'
    )

    return parser


def main():
    #parser = create_argparser()

    #try:
    #    args = parser.parse_args()
    #except argparse.ArgumentError as exc:
    #    print('Error parsing arguments.')
    #    parser.error(str(exc.message))
    #    exit(-1)

    try:

        argc = len(sys.argv[:])
        print("merging... please wait, this is a good time for a coffee or a tea...")

        if argc == 4:
            merger.merge2(sys.argv[1],sys.argv[2],sys.argv[3])
        elif argc == 5:
            merger.merge3(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4])
        else:
            merger.merge(sys.argv[1:(argc-1)], sys.argv[argc-1])
        #merger.merge(os.path.join(os.getcwd(),sys.argv[1]), os.path.join(os.getcwd(),sys.argv[2]), os.path.join(os.getcwd(),sys.argv[3]))

    except:
        print("ERROR:", sys.exc_info())

        print("HELP:")
        print("arguments missing")
        print("structure: ")
        print("biomerge [file1] [file2] ... [fileN] [mergedfile]")
        print("(hint) all file extension should be *.fastq")


if __name__ == '__main__':
    main()
