#!/usr/bin/env python

import os
import argparse
from biomerger import merger
import sys

def create_argparser():
    parser = argparse.ArgumentParser(
        description='fastq merger'
    )

    return parser


def main():
    #parser = create_argparser()

    #try:
    #    args = parser.parse_args()
    #except argparse.ArgumentError as exc:
    #    print('Error parsing arguments.')
    #    parser.error(str(exc.message))
    #    exit(-1)

    try:
        print("merging... please wait, this is a good time for a coffee or a tea...")

        argc = len(sys.argv[:])
        params = []
        for i in range(1,argc-2):
            params.append(sys.arv[i])
        merger.merge(params, sys.argv[argc-1])
        #merger.merge(os.path.join(os.getcwd(),sys.argv[1]), os.path.join(os.getcwd(),sys.argv[2]), os.path.join(os.getcwd(),sys.argv[3]))

    except:
        print("arguments missing")
        print("structure: ")
        print("biomerge [file1] [file2] ... [fileN] [mergedfile]")
        print("(hint) all file extension should be *.fastq")

if __name__ == '__main__':
    main()
